{% set version = '2.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tablehtml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tableHTML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tableHTML/tableHTML_{{ version }}.tar.gz
  sha256: fcaa0e052b7ffdadac13ea5b07f0b00183c16c6e5449017db2cacfd62cc00675

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-jpeg
    - r-magrittr
    - r-png
    - r-shiny
    - r-webshot
  run:
    - r-base
    - r-htmltools
    - r-jpeg
    - r-magrittr
    - r-png
    - r-shiny
    - r-webshot

test:
  commands:
    - $R -e "library('tableHTML')"           # [not win]
    - "\"%R%\" -e \"library('tableHTML')\""  # [win]

about:
  home: https://github.com/LyzandeR/tableHTML
  license: MIT
  summary: A tool to create and style HTML tables with CSS. These can be exported and used in
    any application that accepts HTML (e.g. 'shiny', 'rmarkdown', 'PowerPoint'). It
    also provides functions to create CSS files (which also work with shiny).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
